Add JAXB dependencies
JAXB is no longer available in the JDK since Java 9.
Avoid errors like:
`java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException`